#!/usr/bin/env node
// tools/make-page.mjs — the fixpoint. index.html runs the SAME kernel.mjs the tests and the mutation gate prove, over
// the committed findings: v1's three samples (findings.json) and v2's pre-registered corpus, renders and real counts
// (data/). The v2 headline in README.md and llms.txt is generated from the same kernel, so no v2 number is typed.
// CI regenerates all three and fails if any differs.
import { readFileSync, writeFileSync } from 'node:fs';
const at = (f) => new URL('../' + f, import.meta.url);
const read = (f) => readFileSync(at(f), 'utf8').replace(/\r\n/g, '\n');
const json = (f) => JSON.parse(read(f));
const K = await import(at('kernel.mjs').href);
const kernel = read('kernel.mjs').replace(/^export /gm, '').trimEnd();
const findings = read('findings.json').trim();

const corpus = json('data/corpus.json'), renders = json('data/renders.json'), prereg = json('data/prereg.json');
const cal = json('data/counts-calibration.json'), held = json('data/counts-heldout.json');
const V2 = {
  model: held.model, calibratedAt: cal.measuredAt, heldoutAt: held.measuredAt, metrics: renders.metrics, prereg,
  preregCommit: 'fbeb925', preregSha256: 'f926d3439a6ebc2fe012a2d0a40efb87e80eee5b03cf15c4200afea38ee46ab9',
  samples: corpus.samples.map((s) => ({ id: s.id, shape: s.shape, split: s.split, chars: s.chars, source: s.source, text: s.text })),
  renders: renders.renders.map((r) => ({ id: r.id, width: r.width, height: r.height, formula: r.formula })),
  calibration: cal.rows, heldout: held.rows,
};

// the scored result, through the gated kernel
const rid = Object.fromEntries(V2.renders.map((r) => [r.id, r])), sid = Object.fromEntries(V2.samples.map((s) => [s.id, s]));
const refit = K.fitLaw(cal.rows.map((r) => ({ formula: rid[r.id].formula, real: r.imageTokens })));
if (!refit.ok || refit.a !== prereg.law.a || refit.b !== prereg.law.b) { console.error('the calibration counts no longer give the pre-registered law'); process.exit(1); }
const sc = K.score(held.rows.map((r) => ({ id: r.id, shape: sid[r.id].shape, chars: sid[r.id].chars, textTokens: r.textTokens, formula: rid[r.id].formula, real: r.imageTokens })), prereg.law, prereg.thumb.cStar);
const j = K.judge(sc);
if (!sc.ok || !j.ok) { console.error('the kernel refused the committed data'); process.exit(1); }
const pct = (x) => Math.round(x * 1000) / 10 + '%';
const RULE_TEXT = Object.fromEntries(prereg.rules.map((r) => [r.id, r.rule]));
const L = [];
L.push('**v2 · the crossover law — pre-registered, ' + V2.samples.length + ' samples, ' + j.passed + ' of ' + j.of + ' rules passed.**');
L.push('');
L.push('The real image cost is predictable from pixel size alone: real = ' + prereg.law.a + ' × ceil(w×h/750) + ' + prereg.law.b + ' tokens, fitted on ' + prereg.law.n + ' calibration samples and sealed (commit ' + V2.preregCommit + ') before the ' + sc.n + ' held-out samples were counted. On the held-out samples it was off by ' + sc.medianAbsErrPct + '% at the median and ' + sc.maxAbsErrPct + '% at worst, and with the text token count it picked the cheaper encoding ' + pct(sc.lawAccuracy) + ' of the time. Characters per text token alone — v1\'s framing — picked right only ' + pct(sc.thumbAccuracy) + ' of the time: an image pays for its rendered area, and short lines waste it.');
L.push('');
L.push('| Shape | Cheaper as an image | Mean image vs text |');
L.push('|---|---|---|');
for (const [k, t] of Object.entries(j.tally)) L.push('| ' + k + ' | ' + t.image + ' of ' + t.n + (t.tie ? ' (' + t.tie + ' tied)' : '') + ' | ' + (t.meanPct > 0 ? '+' : '') + t.meanPct + '% |');
L.push('');
L.push('| Pre-registered rule | Result | |');
L.push('|---|---|---|');
for (const r of j.rules) L.push('| ' + RULE_TEXT[r.id] + ' | ' + r.value + ' | ' + (r.pass ? 'PASS' : 'FAIL') + ' |');
L.push('');
L.push('Counts: Anthropic\'s /v1/messages/count_tokens, ' + V2.model + ', text and the rendered PNG for every sample. Cost only: whether a model reads every sample back faithfully was not re-measured at this scale (v1\'s contamination-controlled read was 10/10 on one sample).');
const block = L.join('\n');

const swap = (text, begin, end, body, name) => {
  const a = text.indexOf(begin), b = text.indexOf(end);
  if (a === -1 || b === -1 || b < a) { console.error('markers missing in ' + name + ': ' + begin); process.exit(1); }
  return text.slice(0, a + begin.length) + '\n' + body + '\n' + text.slice(b);
};
const RB = '<!-- ⟦V2-RESULTS-BEGIN⟧ generated by tools/make-page.mjs — do not edit here -->', RE = '<!-- ⟦V2-RESULTS-END⟧ -->';
for (const f of ['README.md', 'llms.txt']) writeFileSync(at(f), swap(read(f), RB, RE, block, f));
let page = read('index.html');
page = swap(page, '// ⟦KERNEL-BEGIN⟧ generated from kernel.mjs by make-page.mjs — do not edit here', '// ⟦KERNEL-END⟧', kernel, 'index.html');
page = swap(page, '// ⟦FINDINGS-BEGIN⟧ generated from findings.json by make-page.mjs — do not edit here', '// ⟦FINDINGS-END⟧', 'const FINDINGS = ' + findings + ';', 'index.html');
page = swap(page, '// ⟦V2-BEGIN⟧ generated from data/ by tools/make-page.mjs — do not edit here', '// ⟦V2-END⟧', 'const V2 = ' + JSON.stringify(V2).replace(/</g, '\\u003c') + ';', 'index.html');
writeFileSync(at('index.html'), page);
console.log('page: kernel ' + kernel.length + ' chars · v2 data ' + JSON.stringify(V2).length + ' chars · ' + j.passed + '/' + j.of + ' rules · median ' + sc.medianAbsErrPct + '% · decision ' + pct(sc.lawAccuracy));
